#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery --app=project.celery_app --workdir=/src inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'
>&2 echo 'Running celery flower service'

celery --app=project.celery_app --workdir=/src flower --port=5555
